// Auto-generated - DO NOT EDIT
// Run 'bun run generate-templates' to regenerate

export const EMBEDDED_TEMPLATES: Map<string, string> = new Map([
  ["base/_gitignore", `# Dependencies
node_modules
.pnp
.pnp.js
__pycache__/
*.py[cod]
.venv/
venv/
env/

# Build outputs
dist
build
*.tsbuildinfo
target/

# Environment variables
.env
.env*.local

# IDEs and editors
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
.idea
*.swp
*.swo
*~
.DS_Store

# Logs
logs
*.log

# Testing
coverage
.nyc_output
.pytest_cache/
.mypy_cache/
.ruff_cache/

# Misc
*.tgz
.cache
tmp
temp
`],
  ["go/addons/air/air.toml.hbs", `# Generated by TriStack. See https://github.com/air-verse/air for options.
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/{{project_slug}} ."
  bin = "./tmp/{{project_slug}}"
  include_ext = ["go", "html", "env"]
  exclude_dir = ["tmp", "bin", "vendor"]

[log]
  time = false

[misc]
  clean_on_exit = true`],
  ["go/addons/docker/_dockerignore", `.git
.gitignore
bin
vendor
.env
.env*.local
Dockerfile
.dockerignore`],
  ["go/addons/docker/docker-compose.yml.hbs", `services:
{{#if (eq database "postgres")}}
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{project_slug}}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
{{else if (eq database "mysql")}}
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: {{project_slug}}
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
{{/if}}

volumes:
{{#if (eq database "postgres")}}
  pgdata:
{{else if (eq database "mysql")}}
  mysqldata:
{{/if}}`],
  ["go/addons/docker/Dockerfile.hbs", `FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /bin/{{project_slug}} .

FROM alpine:3.20

WORKDIR /app
COPY --from=builder /bin/{{project_slug}} .

EXPOSE 8000

ENTRYPOINT ["/app/{{project_slug}}"]`],
  ["go/addons/github-actions/.github/workflows/ci.yml.hbs", `name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install dependencies
        run: go mod tidy
      {{#if (includes addons "golangci-lint")}}
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
      {{/if}}
      {{#if (includes addons "air")}}
      - name: Check for unused
        run: go vet ./...
      {{/if}}
      - name: Test
        run: go test ./...`],
  ["go/addons/golangci-lint/.golangci.yml.hbs", `run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused`],
  ["go/base/_gitignore", `# Binaries
*.exe
*.exe~
*.dll
*.so
*.dylib
bin/
!bin/

# Test binary
*.test

# Output of go coverage
*.out
*.prof

# Dependency directories
vendor/

# Go workspace file
go.work
go.work.sum

# Environment
.env
.env.local

# IDE
.idea
.vscode
*.swp`],
  ["go/base/.gitkeep", ``],
  ["go/base/env.example.hbs", `# Copy this file to \`.env\` and adjust values for your environment.

# The application name / debug flag
APP_NAME={{projectName}}
DEBUG=false

# The port the server listens on
PORT=8000

{{#if (ne database "none")}}
# Database URL.
# SQLite:  {{project_slug}}.db
# Postgres: postgres://postgres:postgres@localhost:5432/{{project_slug}}
# MySQL:   mysql://root:password@localhost:3306/{{project_slug}}
DATABASE_URL={{#if (eq database "sqlite")}}{{project_slug}}.db{{else if (eq database "postgres")}}postgres://postgres:postgres@localhost:5432/{{project_slug}}{{else if (eq database "mysql")}}mysql://root:password@localhost:3306/{{project_slug}}{{/if}}
{{/if}}`],
  ["go/base/go.mod.hbs", `module {{project_slug}}

go 1.22

{{#if (eq framework "gin")}}
require github.com/gin-gonic/gin v1.10.0
{{else if (eq framework "fiber")}}
require github.com/gofiber/fiber/v2 v2.52.5
{{else if (eq framework "echo")}}
require github.com/labstack/echo/v4 v4.12.0
{{else if (eq framework "chi")}}
require github.com/go-chi/chi/v5 v5.1.0
{{/if}}

{{#if (eq orm "gorm")}}
require gorm.io/gorm v1.25.12
{{#if (eq database "sqlite")}}
require gorm.io/driver/sqlite v1.5.7
{{else if (eq database "postgres")}}
require gorm.io/driver/postgres v1.5.9
{{else if (eq database "mysql")}}
require gorm.io/driver/mysql v1.5.7
{{/if}}
{{else if (eq orm "sqlx")}}
require github.com/jmoiron/sqlx v1.4.0
{{#if (eq database "sqlite")}}
require modernc.org/sqlite v1.34.1
{{else if (eq database "postgres")}}
require github.com/jackc/pgx/v5 v5.7.1
{{else if (eq database "mysql")}}
require github.com/go-sql-driver/mysql v1.8.1
{{/if}}
{{else if (eq orm "sqlc")}}
{{#if (eq database "sqlite")}}
require modernc.org/sqlite v1.34.1
{{else if (eq database "postgres")}}
require github.com/jackc/pgx/v5 v5.7.1
{{else if (eq database "mysql")}}
require github.com/go-sql-driver/mysql v1.8.1
{{/if}}
{{/if}}

{{#if (eq migrations "goose")}}
require github.com/pressly/goose/v3 v3.22.1
{{else if (eq migrations "golang-migrate")}}
require github.com/golang-migrate/migrate/v4 v4.18.1
{{/if}}`],
  ["go/framework/chi/main.go.hbs", `// {{projectName}} - a Go backend scaffolded with TriStack.
package main

import (
	"log"
	"net/http"
	"os"

	"github.com/go-chi/chi/v5"
)

func main() {
	r := chi.NewRouter()

	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(\`{"status":"ok"}\`))
	})

	port := os.Getenv("PORT")
	if port == "" {
		port = "8000"
	}

	name := os.Getenv("APP_NAME")
	if name == "" {
		name = "{{projectName}}"
	}

	log.Printf("%s listening on :%s", name, port)
	if err := http.ListenAndServe(":"+port, r); err != nil {
		log.Fatal(err)
	}
}`],
  ["go/framework/echo/main.go.hbs", `// {{projectName}} - a Go backend scaffolded with TriStack.
package main

import (
	"log"
	"net/http"
	"os"

	"github.com/labstack/echo/v4"
)

func main() {
	e := echo.New()

	e.GET("/health", func(c echo.Context) error {
		return c.JSON(http.StatusOK, map[string]string{"status": "ok"})
	})

	port := os.Getenv("PORT")
	if port == "" {
		port = "8000"
	}

	name := os.Getenv("APP_NAME")
	if name == "" {
		name = "{{projectName}}"
	}

	log.Printf("%s listening on :%s", name, port)
	if err := e.Start(":" + port); err != nil {
		log.Fatal(err)
	}
}`],
  ["go/framework/fiber/main.go.hbs", `// {{projectName}} - a Go backend scaffolded with TriStack.
package main

import (
	"log"
	"os"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	app.Get("/health", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"status": "ok"})
	})

	port := os.Getenv("PORT")
	if port == "" {
		port = "8000"
	}

	name := os.Getenv("APP_NAME")
	if name == "" {
		name = "{{projectName}}"
	}

	log.Printf("%s listening on :%s", name, port)
	if err := app.Listen(":" + port); err != nil {
		log.Fatal(err)
	}
}`],
  ["go/framework/gin/main.go.hbs", `// {{projectName}} - a Go backend scaffolded with TriStack.
package main

import (
	"log"
	"net/http"
	"os"

	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()

	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	port := os.Getenv("PORT")
	if port == "" {
		port = "8000"
	}

	app := os.Getenv("APP_NAME")
	if app == "" {
		app = "{{projectName}}"
	}

	log.Printf("%s listening on :%s", app, port)
	if err := r.Run(":" + port); err != nil {
		log.Fatal(err)
	}
}`],
  ["go/framework/stdlib/main.go.hbs", `// {{projectName}} - a Go backend scaffolded with TriStack.
package main

import (
	"log"
	"net/http"
	"os"
)

func main() {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(\`{"status":"ok"}\`))
	})

	port := os.Getenv("PORT")
	if port == "" {
		port = "8000"
	}

	log.Printf("%s listening on :%s", appName(), port)
	if err := http.ListenAndServe(":"+port, mux); err != nil {
		log.Fatal(err)
	}
}

func appName() string {
	name := os.Getenv("APP_NAME")
	if name == "" {
		return "{{projectName}}"
	}
	return name
}`],
  ["go/migrations/golang-migrate/db/migrations/0001_create_items.down.sql.hbs", `DROP TABLE items;`],
  ["go/migrations/golang-migrate/db/migrations/0001_create_items.up.sql.hbs", `CREATE TABLE items (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);`],
  ["go/migrations/goose/migrations/0001_create_items.sql.hbs", `-- +goose Up
CREATE TABLE items (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE items;`],
  ["go/orm/gorm/internal/db/db.go.hbs", `// Package db provides GORM-based database access for {{projectName}}.
package db

import (
	"os"

	"gorm.io/driver/mysql"
	"gorm.io/driver/postgres"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

// Connect opens a GORM connection using the DATABASE_URL environment variable.
func Connect() (*gorm.DB, error) {
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		dsn = "{{#if (eq database "sqlite")}}{{project_slug}}.db{{else if (eq database "postgres")}}postgres://postgres:postgres@localhost:5432/{{project_slug}}{{else if (eq database "mysql")}}mysql://root:password@localhost:3306/{{project_slug}}{{/if}}"
	}

{{#if (eq database "sqlite")}}
	return gorm.Open(sqlite.Open(dsn), &gorm.Config{})
{{else if (eq database "postgres")}}
	return gorm.Open(postgres.Open(dsn), &gorm.Config{})
{{else if (eq database "mysql")}}
	return gorm.Open(mysql.Open(dsn), &gorm.Config{})
{{else}}
	return gorm.Open(sqlite.Open(dsn), &gorm.Config{})
{{/if}}
}

// AutoMigrate creates or updates the tables defined by the models.
func AutoMigrate(db *gorm.DB) error {
	return db.AutoMigrate(&Item{})
}`],
  ["go/orm/gorm/internal/db/models.go.hbs", `package db

import "time"

// Item is an example model. Replace or remove as needed.
type Item struct {
	ID        string    \`gorm:"primaryKey" json:"id"\`
	Name      string    \`json:"name"\`
	CreatedAt time.Time \`json:"created_at"\`
}`],
  ["go/orm/sqlc/internal/db/db.go.hbs", `// Package db provides database/sql access for {{projectName}} via sqlc.
package db

import (
	"database/sql"
	"os"
{{#if (eq database "sqlite")}}
	_ "modernc.org/sqlite"
{{else if (eq database "postgres")}}
	_ "github.com/jackc/pgx/v5/stdlib"
{{else if (eq database "mysql")}}
	_ "github.com/go-sql-driver/mysql"
{{/if}}
)

// Connect opens a database handle using the DATABASE_URL environment variable.
func Connect() (*sql.DB, error) {
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		dsn = "{{#if (eq database "sqlite")}}{{project_slug}}.db{{else if (eq database "postgres")}}postgres://postgres:postgres@localhost:5432/{{project_slug}}{{else if (eq database "mysql")}}mysql://root:password@localhost:3306/{{project_slug}}{{/if}}"
	}

{{#if (eq database "sqlite")}}
	return sql.Open("sqlite", dsn)
{{else if (eq database "postgres")}}
	return sql.Open("pgx", dsn)
{{else if (eq database "mysql")}}
	return sql.Open("mysql", dsn)
{{else}}
	return sql.Open("sqlite", dsn)
{{/if}}
}`],
  ["go/orm/sqlc/sqlc.yaml.hbs", `version: "2"
sql:
  - engine: "sqlite" # Set to postgresql or mysql as needed
    queries: "queries"
    schema: "schema"
    gen:
      go:
        package: "store"
        out: "internal/store"
        sql_package: "database/sql"`],
  ["go/orm/sqlx/internal/db/db.go.hbs", `// Package db provides sqlx-based database access for {{projectName}}.
package db

import (
	"os"

	"github.com/jmoiron/sqlx"
{{#if (eq database "sqlite")}}
	_ "modernc.org/sqlite"
{{else if (eq database "postgres")}}
	_ "github.com/jackc/pgx/v5/stdlib"
{{else if (eq database "mysql")}}
	_ "github.com/go-sql-driver/mysql"
{{/if}}
)

// Connect opens a sqlx connection using the DATABASE_URL environment variable.
func Connect() (*sqlx.DB, error) {
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		dsn = "{{#if (eq database "sqlite")}}{{project_slug}}.db{{else if (eq database "postgres")}}postgres://postgres:postgres@localhost:5432/{{project_slug}}{{else if (eq database "mysql")}}mysql://root:password@localhost:3306/{{project_slug}}{{/if}}"
	}

{{#if (eq database "sqlite")}}
	return sqlx.Open("sqlite", dsn)
{{else if (eq database "postgres")}}
	return sqlx.Open("pgx", dsn)
{{else if (eq database "mysql")}}
	return sqlx.Open("mysql", dsn)
{{else}}
	return sqlx.Open("sqlite", dsn)
{{/if}}
}`],
  ["python/addons/docker/_dockerignore", `.git
.gitignore
.venv
venv
__pycache__
*.pyc
.pytest_cache
.mypy_cache
.ruff_cache
.env
.env*.local
Dockerfile
.dockerignore
`],
  ["python/addons/docker/docker-compose.yml.hbs", `services:
{{#if (eq database "postgres")}}
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{project_slug}}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
{{else if (eq database "mysql")}}
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: {{project_slug}}
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
{{/if}}

volumes:
{{#if (eq database "postgres")}}
  pgdata:
{{else if (eq database "mysql")}}
  mysqldata:
{{/if}}
`],
  ["python/addons/docker/Dockerfile.hbs", `FROM python:3.12-slim

WORKDIR /app

# Install uv for dependency management
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install dependencies first for better layer caching
COPY pyproject.toml ./
RUN uv sync --no-install-project --no-dev

# Copy the rest of the application
COPY . .

ENV PYTHONPATH=/app
EXPOSE 8000

CMD ["uv", "run", "uvicorn", "{{project_slug}}.main:app", "--host", "0.0.0.0", "--port", "8000"]
`],
  ["python/addons/github-actions/.github/workflows/ci.yml.hbs", `name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync
      {{#if (includes addons "ruff")}}
      - name: Lint
        run: uv run ruff check .
      {{/if}}
      {{#if (includes addons "mypy")}}
      - name: Type check
        run: uv run mypy .
      {{/if}}
      {{#if (includes addons "pytest")}}
      - name: Test
        run: uv run pytest
      {{/if}}
`],
  ["python/addons/mypy/mypy.ini.hbs", `[mypy]
python_version = "3.12"
strict = true
warn_unused_configs = true
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = "{{project_slug}}.*"
follow_imports = "normal"
`],
  ["python/addons/pytest/tests/test_health.py.hbs", `from fastapi.testclient import TestClient

from {{project_slug}}.main import app

client = TestClient(app)


def test_health():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}
`],
  ["python/addons/ruff/ruff.toml.hbs", `line-length = 100
target-version = "py312"

[lint]
select = ["E", "F", "I", "UP", "B"]
ignore = []

[lint.isort]
known-first-party = ["{{project_slug}}"]
`],
  ["python/base/{{project_slug}}/__init__.py.hbs", `"""{{projectName}} - a {{framework}} backend scaffolded with TriStack."""
`],
  ["python/base/{{project_slug}}/config.py.hbs", `"""Application configuration.

Environment variables are read from a \`.env\` file at the project root. Copy
\`.env.example\` to \`.env\` and adjust values as needed.
"""
from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    app_name: str = "{{projectName}}"
    debug: bool = False

    {{#if (ne database "none")}}
    database_url: str = "{{#if (eq database "sqlite")}}sqlite+aiosqlite:///./{{project_slug}}.db{{else if (eq database "postgres")}}postgresql+asyncpg://postgres:postgres@localhost:5432/{{project_slug}}{{else if (eq database "mysql")}}mysql+asyncmy://root:password@localhost:3306/{{project_slug}}{{/if}}"
    {{/if}}


@lru_cache
def get_settings() -> Settings:
    return Settings()
`],
  ["python/base/env.example.hbs", `# Copy this file to \`.env\` and adjust values for your environment.

# The application name / debug flag
APP_NAME={{projectName}}
DEBUG=false

{{#if (ne database "none")}}
# Database URL.
# SQLite:  sqlite+aiosqlite:///./{{project_slug}}.db
# Postgres: postgresql+asyncpg://postgres:postgres@localhost:5432/{{project_slug}}
# MySQL:   mysql+asyncmy://root:password@localhost:3306/{{project_slug}}
DATABASE_URL=sqlite+aiosqlite:///./{{project_slug}}.db
{{/if}}
`],
  ["python/base/pyproject-pip.toml.hbs", `[project]
name = "{{project_slug}}"
version = "0.1.0"
description = "{{projectName}} - a {{framework}} backend"
requires-python = ">=3.12"
dependencies = [
    "pydantic-settings",
{{#if (eq framework "fastapi")}}
    "fastapi",
    "uvicorn[standard]",
{{else if (eq framework "litestar")}}
    "litestar",
{{else if (eq framework "django")}}
    "django",
    "djangorestframework",
    "django-cors-headers",
{{else if (eq framework "flask")}}
    "flask",
{{/if}}
{{#if (eq orm "sqlmodel")}}
    "sqlmodel",
{{else if (eq orm "sqlalchemy")}}
    "sqlalchemy[asyncio]",
{{else if (eq orm "tortoise")}}
    "tortoise-orm",
{{/if}}
{{#if (eq migrations "alembic")}}
    "alembic",
{{/if}}
{{#if (eq database "postgres")}}
    "asyncpg",
{{else if (eq database "mysql")}}
    "asyncmy",
{{else if (eq database "sqlite")}}
    "aiosqlite",
{{/if}}
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "mypy",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["{{project_slug}}"]
`],
  ["python/base/pyproject-poetry.toml.hbs", `[tool.poetry]
name = "{{project_slug}}"
version = "0.1.0"
description = "{{projectName}} - a {{framework}} backend"
authors = []
packages = [{ include = "{{project_slug}}" }]

[tool.poetry.dependencies]
python = ">=3.12"
pydantic-settings = "^2.7"
{{#if (eq framework "fastapi")}}
fastapi = "^0.115"
uvicorn = { extras = ["standard"], version = "^0.34" }
{{else if (eq framework "litestar")}}
litestar = "^2.14"
{{else if (eq framework "django")}}
django = "^5.1"
djangorestframework = "^3.15"
django-cors-headers = "^4.6"
{{else if (eq framework "flask")}}
flask = "^3.1"
{{/if}}
{{#if (eq orm "sqlmodel")}}
sqlmodel = "^0.0.22"
{{else if (eq orm "sqlalchemy")}}
sqlalchemy = { extras = ["asyncio"], version = "^2.0" }
{{else if (eq orm "tortoise")}}
tortoise-orm = "^0.24"
{{/if}}
{{#if (eq migrations "alembic")}}
alembic = "^1.14"
{{/if}}
{{#if (eq database "postgres")}}
asyncpg = "^0.30"
{{else if (eq database "mysql")}}
asyncmy = "^0.2"
{{else if (eq database "sqlite")}}
aiosqlite = "^0.20"
{{/if}}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
`],
  ["python/base/pyproject-uv.toml.hbs", `[project]
name = "{{project_slug}}"
version = "0.1.0"
description = "{{projectName}} - a {{framework}} backend"
requires-python = ">=3.12"
dependencies = [
    "pydantic-settings",
{{#if (eq framework "fastapi")}}
    "fastapi",
    "uvicorn[standard]",
{{else if (eq framework "litestar")}}
    "litestar",
{{else if (eq framework "django")}}
    "django",
    "djangorestframework",
    "django-cors-headers",
{{else if (eq framework "flask")}}
    "flask",
{{/if}}
{{#if (eq orm "sqlmodel")}}
    "sqlmodel",
{{else if (eq orm "sqlalchemy")}}
    "sqlalchemy[asyncio]",
{{else if (eq orm "tortoise")}}
    "tortoise-orm",
{{/if}}
{{#if (eq migrations "alembic")}}
    "alembic",
{{/if}}
{{#if (eq database "postgres")}}
    "asyncpg",
{{else if (eq database "mysql")}}
    "asyncmy",
{{else if (eq database "sqlite")}}
    "aiosqlite",
{{/if}}
]

[dependency-groups]
dev = [
{{#if (includes addons "ruff")}}
    "ruff",
{{/if}}
{{#if (includes addons "mypy")}}
    "mypy",
{{/if}}
{{#if (includes addons "pytest")}}
    "pytest",
    "httpx",
{{/if}}
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["{{project_slug}}"]
`],
  ["python/framework/django/{{project_slug}}/__init__.py.hbs", `from .config import get_settings

settings = get_settings()
`],
  ["python/framework/django/{{project_slug}}/asgi.py.hbs", `"""ASGI config for {{projectName}}."""
import os

from django.core.asgi import get_asgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{{project_slug}}.settings")

application = get_asgi_application()
`],
  ["python/framework/django/{{project_slug}}/core/__init__.py", ``],
  ["python/framework/django/{{project_slug}}/core/apps.py.hbs", `from django.apps import AppConfig


class CoreConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "{{project_slug}}.core"
`],
  ["python/framework/django/{{project_slug}}/core/urls.py", `from django.urls import path

from . import views

urlpatterns = [
    path("health/", views.health),
]
`],
  ["python/framework/django/{{project_slug}}/core/views.py", `from rest_framework.decorators import api_view
from rest_framework.response import Response


@api_view(["GET"])
def health(request):
    return Response({"status": "ok"})
`],
  ["python/framework/django/{{project_slug}}/settings.py.hbs", `"""
Django settings for {{projectName}}.
"""
import os
from pathlib import Path

from .config import get_settings

settings = get_settings()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-change-me")
DEBUG = settings.debug
ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "{{project_slug}}.core",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "{{project_slug}}.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "{{project_slug}}.wsgi.application"
ASGI_APPLICATION = "{{project_slug}}.asgi.application"

{{#if (eq database "none")}}
DATABASES = {}
{{else if (eq database "sqlite")}}
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
{{else if (eq database "postgres")}}
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "{{project_slug}}"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}
{{else if (eq database "mysql")}}
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("MYSQL_DATABASE", "{{project_slug}}"),
        "USER": os.environ.get("MYSQL_USER", "root"),
        "PASSWORD": os.environ.get("MYSQL_PASSWORD", "password"),
        "HOST": os.environ.get("MYSQL_HOST", "localhost"),
        "PORT": os.environ.get("MYSQL_PORT", "3306"),
    }
}
{{/if}}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {}
`],
  ["python/framework/django/{{project_slug}}/urls.py.hbs", `"""URL configuration for {{projectName}}."""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("{{project_slug}}.core.urls")),
]
`],
  ["python/framework/django/{{project_slug}}/wsgi.py.hbs", `"""WSGI config for {{projectName}}."""
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{{project_slug}}.settings")

application = get_wsgi_application()
`],
  ["python/framework/django/manage.py.hbs", `#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys


def main():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{{project_slug}}.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed?",
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
`],
  ["python/framework/fastapi/{{project_slug}}/main.py.hbs", `"""FastAPI application entrypoint for {{projectName}}."""
from contextlib import asynccontextmanager

from fastapi import FastAPI

from .config import get_settings

settings = get_settings()


{{#if (and (ne database "none") (eq migrations "none"))}}
@asynccontextmanager
async def lifespan(app: FastAPI):
    from .db import init_db

    await init_db()
    yield
{{else}}
@asynccontextmanager
async def lifespan(app: FastAPI):
    yield
{{/if}}


app = FastAPI(title=settings.app_name, lifespan=lifespan)

{{#if (ne database "none")}}
from .db import get_session  # noqa: E402


@app.get("/health")
async def health():
    return {"status": "ok"}
{{else}}
@app.get("/health")
async def health():
    return {"status": "ok"}
{{/if}}
`],
  ["python/framework/flask/{{project_slug}}/main.py.hbs", `"""Flask application entrypoint for {{projectName}}."""
from flask import Flask, jsonify

from .config import get_settings

settings = get_settings()

app = Flask(__name__)
app.config["DEBUG"] = settings.debug


@app.get("/health")
def health():
    return jsonify({"status": "ok"})
`],
  ["python/framework/litestar/{{project_slug}}/main.py.hbs", `"""Litestar application entrypoint for {{projectName}}."""
from litestar import Litestar, get

from .config import get_settings

settings = get_settings()


@get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


app = Litestar(
    route_handlers=[health],
    debug=settings.debug,
)
`],
  ["python/migrations/alembic/alembic.ini", `# Alembic configuration for {{projectName}}
[alembic]
script_location = migrations
prepend_sys_path = .
sqlalchemy.url =

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
`],
  ["python/migrations/alembic/migrations/env.py.hbs", `"""Alembic migration environment.

Url is read from the application settings so a single config works for
SQLite, Postgres, and MySQL automatically.
"""
import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlmodel import SQLModel

{{#if (eq orm "sqlmodel")}}
from {{project_slug}}.config import get_settings
from {{project_slug}}.models import Item  # noqa: F401  (registers tables on SQLModel.metadata)
{{else if (eq orm "sqlalchemy")}}
from {{project_slug}}.config import get_settings
from {{project_slug}}.models import Base
{{/if}}

config = context.config
{{#if (eq orm "sqlmodel")}}
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = SQLModel.metadata
{{else if (eq orm "sqlalchemy")}}
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata
{{/if}}

settings = get_settings()


def run_migrations_offline() -> None:
    url = settings.database_url
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata, compare_type=True)

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = settings.database_url

    connectable = async_engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
`],
  ["python/migrations/alembic/migrations/script.py.mako", `"""\${message}

Revision ID: \${up_revision}
Revises: \${down_revision | comma,n}
Create Date: \${create_date}

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
\${imports if imports else ""}

# revision identifiers, used by Alembic.
revision: str = \${repr(up_revision)}
down_revision: Union[str, None] = \${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = \${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = \${repr(depends_on)}


def upgrade() -> None:
    \${upgrades if upgrades else "pass"}


def downgrade() -> None:
    \${downgrades if downgrades else "pass"}
`],
  ["python/migrations/alembic/migrations/versions/README.md", `# Alembic migration versions are generated with:

# uv run alembic revision --autogenerate -m "initial"

# Generated revisions are placed in this directory.
`],
  ["python/orm/sqlmodel/{{project_slug}}/db.py.hbs", `"""Database engine and session management using SQLModel."""
from collections.abc import AsyncGenerator

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlmodel import SQLModel

from .config import get_settings

settings = get_settings()

engine = create_async_engine(settings.database_url, echo=settings.debug)
SessionLocal = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


async def get_session() -> AsyncGenerator[AsyncSession, None]:
    """FastAPI dependency that yields a database session."""
    async with SessionLocal() as session:
        yield session


{{#if (eq migrations "none")}}
async def init_db() -> None:
    """Create all tables (used when migrations are not enabled)."""
    # Import models so they are registered on the metadata before create_all.
    from . import models  # noqa: F401

    async with engine.begin() as conn:
        await conn.run_sync(SQLModel.metadata.create_all)
{{/if}}
`],
  ["python/orm/sqlmodel/{{project_slug}}/models.py.hbs", `"""SQLModel models for {{projectName}}."""
from datetime import datetime, timezone
from uuid import uuid4

from sqlmodel import Field, SQLModel


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Item(SQLModel, table=True):
    """Example model. Replace or remove as needed."""

    id: str = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    name: str
    created_at: datetime = Field(default_factory=utcnow)
`],
  ["rust/base/.gitkeep", ``]
]);

export const TEMPLATE_COUNT = 57;
